### ISSUE TITLE
Suggest splitting CamelCase into 2 functions

### ISSUE THREAD

**Issue by natefinch** [codemodus/kace#2]
It can make a big difference in usability to avoid using booleans in function signatures, since it's impossible to tell what true or false mean when you're just reading code.

I suggest using CamelCase and PascalCase as function names (where PascalCase is the  first upper and camel is first lower).

I'd also like to have any functions that need to use the intiialisms list to have an alternate form that takes a customized list.

I'm happy to make PRs for any of this.

**Comment by daved** [comment]
I can't recall the exact use case; The reason for the bool was something like "it's easier to swap a bool than to swap an entire function".  However, this was years ago and I can't attest to the quality of my rationale (especially because I was less functional-minded).  I'd be happy to implement your suggestion, and I greatly appreciate the PR offer.

**Comment by natefinch** [comment]
Cool, yeah, it also makes it easier to use in templates (which happens to be my use case)

**Comment by daved** [comment]
Closed by #4
